services:
  db:
    image: postgres:latest
    container_name: postgres_recipes_db
    environment:
      POSTGRES_USER: davidhsb
      POSTGRES_PASSWORD: 2923
      POSTGRES_DB: lacuna_recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: recipes_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      ./.env
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  postgres_data:
