version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_recipes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lacuna_recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: recipes_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://davidhsb:2923@localhost:5432/lacuna_recipes?schema=public"
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  postgres_data:
